### ISSUE TITLE
Sentiment Analysis module - "enable_network_isolation" error 

### ISSUE THREAD

**Issue by DanielTatarkin** [awslabs/amazon-sagemaker-workshop#12]
When going through [Introduction to Amazon SageMaker](https://github.com/awslabs/amazon-sagemaker-workshop/tree/master/Introduction) module [Sentiment Analysis](https://github.com/awslabs/amazon-sagemaker-workshop/blob/master/modules/Sentiment_Analysis.md), I'm getting: `TypeError: type object got multiple values for keyword argument 'enable_network_isolation'` 

This happens in cell 13 when creating a transformer: 
`transformer = estimator.transformer(instance_count=1, instance_type='ml.c5.xlarge')`

Similar problem outlined here: https://forums.aws.amazon.com/thread.jspa?threadID=321194

I tried using different Kernels, creating a brand new Notebook instance and restarting it. Other modules have been working without issues. Anything that could be suggested?

Thanks,
Daniel Tatarkin 

Screenshot (Same error using conda_tensorflow_p36 default kernel, but this screenshot was taken when I tried conda_amazonei_tensorflow_p36)
![image](https://user-images.githubusercontent.com/16328369/83552562-95679300-a4cf-11ea-897c-4aacdab9b87b.png)

**Comment by DanielTatarkin** [comment]
Manually updating SageMaker SDK helped solve the issue. 

`!pip install sagemaker --upgrade`

**Comment by rabowskyb** [comment]
Hello, yes sorry about that issue -- what is happening is SageMaker notebook instances have an older version of the SageMaker Python SDK with that bug, which has been fixed in the latest version.  I have informed the SageMaker service team, they are working on getting the new version into notebook instances.

**Comment by nilloBE** [comment]
> Manually updating SageMaker SDK helped solve the issue.
> 
> `!pip install sagemaker --upgrade`

Can you confirm this fixed this for you? I have tried doing this and it's not working for me ... I upgraded boto3 too but to no avail.

**Comment by nilloBE** [comment]
> > Manually updating SageMaker SDK helped solve the issue.
> > `!pip install sagemaker --upgrade`
> 
> Can you confirm this fixed this for you? I have tried doing this and it's not working for me ... I upgraded boto3 too but to no avail.

Nevermind my comment - restarted the notebook and upgraded at the beginning and it is working indeed. Thanks! :-)
