### ISSUE TITLE
[Image Classification with Transfer Learning] Dead-link to Example Image

### ISSUE THREAD

**Issue by MarrickLip** [awslabs/amazon-sagemaker-workshop#14]
Hi,

I'm following the 'Image Classification with Transfer Learning' module and are getting a 404 error trying to download the sample image from the Caltech256 dataset at [http://www.vision.caltech.edu/Image_Datasets/Caltech256/images/008.bathtub/008_0007.jpg](http://www.vision.caltech.edu/Image_Datasets/Caltech256/images/008.bathtub/008_0007.jpg)

This maybe a blip e.g. it comes back online shortly. However, their [website](http://www.vision.caltech.edu/Image_Datasets/Caltech256/) does say "Please do not link directly to these images: it overloads our server." -- perhaps it might be better if you guys start hosting the image (or just including it in the Git repo)

<img width="1798" alt="Screen Shot 2020-08-22 at 1 01 27 AM" src="https://user-images.githubusercontent.com/24652534/90893408-048bbe00-e413-11ea-9a17-d4d9ba1df3cf.png">

**Comment by rabowskyb** [comment]
Thanks for pointing this out!  I pushed up a fix, following your suggestion to include the image here in GitHub.
