### ISSUE TITLE
Computer Vision Use Case: Image Classification - Dead Link to Batch Transform Data

### ISSUE THREAD

**Issue by mthomp89** [awslabs/amazon-sagemaker-workshop#17]
Following the 'Image Classification Full Training' module and getting a 404 error trying to download the Caltech256 dataset required for the batch transform portion of model deployment. Link is http://www.vision.caltech.edu/Image_Datasets/Caltech256/images/008.bathtub/ which leads to 

![2021-04-16 12_42_11-S3 Bucket Listing Generator](https://user-images.githubusercontent.com/37227520/115057016-83a59900-9eb1-11eb-9379-bd2ccd82c954.png)

**Comment by rabowskyb** [comment]
Hello, thanks for checking in -- we have reviewed the Image Classification notebook used in the Introduction workshop.  The link is https://github.com/awslabs/amazon-sagemaker-workshop/blob/master/notebooks/Image-classification-transfer-learning.ipynb.  That notebook uses a test bathtub image that is fetched from GitHub, not the URL you linked above.  Are you using a different notebook that is not part of the Introduction workshop?  

Please use the notebook linked in this comment.  For now, we'll close this issue, if there are issues with the notebook linked in this comment, please let us know and open a new issue.

**Comment by mthomp89** [comment]
Yes, different notebook. Just realized that. Thank you.
