### ISSUE TITLE
In place column y update

### ISSUE THREAD

**Issue by russau** [awslabs/amazon-sagemaker-workshop#2]
https://github.com/awslabs/amazon-sagemaker-workshop/blob/491621041bac397275340c25cfa6a670b6fb5f69/notebooks/video-game-sales-xgboost.ipynb#L257

Tiny issue: running this cell twice sets `y` to `no` for every row.  Small issue but this is very easy to accidentally do in a notebook.

**Comment by rabowskyb** [comment]
Committed a fix.
