### ISSUE TITLE
Numpy error in sentiment analysis jupyter notebook(s)

### ISSUE THREAD

**Issue by limivorous** [awslabs/amazon-sagemaker-workshop#5]
Within the sentiment analysis jupyter notebook (sentiment-analysis.ipynb) you receive an error, which makes it unusable, when trying to run:
`(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)`
Error:
`ValueError: Object arrays cannot be loaded when allow_pickle=False`

**Comment by rabowskyb** [comment]
This was due to a Numpy version incompatability with Keras datasets; a fix has been pushed.
